services:
  - type: web
    name: chat-file-storage
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://chat-website-app.web.app,https://chat-website-app.firebaseapp.com,http://localhost:3000